// Generates platform icon code from design/icons.json, so app and web share glyphs.
//   node design/tools/gen-icons.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const { icons } = JSON.parse(readFileSync(join(root, 'design/icons.json'), 'utf8'));
const pascal = (s) => s.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const header = 'Generated by design/tools/gen-icons.mjs from design/icons.json. Do not edit.';

// Android: lazily built ImageVectors.
const kt = `// ${header}
package app.musicremote.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/** Material Symbols Rounded, filled. */
object AuxIcons {
${Object.entries(icons).map(([n, d]) => `    val ${pascal(n)}: ImageVector by lazy { icon("${n}", "${d}") }`).join('\n')}

    // Symbols use a 960-unit viewport shifted up by 960; move it back into view.
    private fun icon(name: String, path: String): ImageVector =
        ImageVector.Builder(
            name = name,
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f,
        )
            .addGroup(translationY = 960f)
            .addPath(pathData = addPathNodes(path), fill = SolidColor(Color.Black))
            .clearGroup()
            .build()
}
`;
const ktPath = join(root, 'android/app/src/main/java/app/musicremote/ui/icons/AuxIcons.kt');
mkdirSync(dirname(ktPath), { recursive: true });
writeFileSync(ktPath, kt);

// Web: path strings keyed by name.
const ts = `// ${header}
export const ICON_VIEWBOX = '0 -960 960 960';
export const icons = {
${Object.entries(icons).map(([n, d]) => `  ${n}: '${d}',`).join('\n')}
} as const;
export type IconName = keyof typeof icons;
`;
const tsPath = join(root, 'web/src/ui/icons.ts');
mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(tsPath, ts);
console.log(`${Object.keys(icons).length} icons -> AuxIcons.kt, web/src/ui/icons.ts`);
