// Brand mark: an M3 Expressive 9-sided cookie holding a music note.
// Generates the Android adaptive/monochrome launcher icon, notification icon,
// and the web favicon + maskable PWA icon from one geometry.
//   node design/tools/gen-brand.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const { icons } = JSON.parse(readFileSync(join(root, 'design/icons.json'), 'utf8'));
const BRAND = '#7B5CFF';
const BRAND_DEEP = '#4B2FD1';
const NOTE = icons.music_note; // viewBox 0 -960 960 960

/** Cookie outline centred in a square of `size`, radius r: matches web shapes.ts. */
function cookie(cx, cy, r, points = 9, steps = 360) {
  const out = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * Math.PI * 2;
    const rr = r * (0.9 + 0.1 * Math.cos(points * (t + Math.PI / 2)));
    out.push(`${i ? 'L' : 'M'}${(cx + Math.cos(t) * rr).toFixed(2)},${(cy + Math.sin(t) * rr).toFixed(2)}`);
  }
  return out.join('') + 'Z';
}


/** Uniformly scales + translates SVG path data (absolute and relative commands). */
function transformPath(d, scale, tx, ty) {
  const tokens = d.match(/[a-zA-Z]|-?\d*\.?\d+(?:e-?\d+)?/g);
  const out = [];
  let cmd = "";
  let i = 0;
  const num = () => parseFloat(tokens[i++]);
  const f = (n) => +n.toFixed(3);
  const arity = { M: 2, L: 2, H: 1, V: 1, C: 6, S: 4, Q: 4, T: 2, A: 7, Z: 0 };
  while (i < tokens.length) {
    if (/[a-zA-Z]/.test(tokens[i])) { cmd = tokens[i++]; out.push(cmd); if (cmd.toUpperCase() === "Z") continue; }
    const up = cmd.toUpperCase();
    const abs = cmd === up;
    const n = arity[up];
    const vals = Array.from({ length: n }, num);
    let mapped;
    if (up === "H") mapped = [abs ? vals[0] * scale + tx : vals[0] * scale];
    else if (up === "V") mapped = [abs ? vals[0] * scale + ty : vals[0] * scale];
    else if (up === "A") mapped = [vals[0] * scale, vals[1] * scale, vals[2], vals[3], vals[4], abs ? vals[5] * scale + tx : vals[5] * scale, abs ? vals[6] * scale + ty : vals[6] * scale];
    else mapped = vals.map((v, k) => (abs ? v * scale + (k % 2 ? ty : tx) : v * scale));
    out.push(mapped.map(f).join(","));
  }
  return out.join(" ");
}

const write = (rel, text) => {
  const p = join(root, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, text);
  console.log('wrote', rel);
};

// ---------------------------------------------------------------- Android
// Adaptive icons are 108dp with a 66dp safe circle; keep the cookie inside it.
const A = 108;
const cookieA = cookie(54, 54, 31);
// Note scaled into the cookie: symbol box 960 -> 30dp.
const noteScale = 30 / 960;
const noteGroup = (fill) => `    <group android:scaleX="${noteScale}" android:scaleY="${noteScale}" android:translateX="${54 - 15}" android:translateY="${54 + 15}">
        <path android:fillColor="${fill}" android:pathData="${NOTE}" />
    </group>`;

write('android/app/src/main/res/drawable/ic_launcher_background.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/tools/gen-brand.mjs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${A}dp" android:height="${A}dp" android:viewportWidth="${A}" android:viewportHeight="${A}">
    <path android:pathData="M0,0h${A}v${A}h-${A}z">
        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="${A}" android:endY="${A}">
                <item android:offset="0" android:color="${BRAND}" />
                <item android:offset="1" android:color="${BRAND_DEEP}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
`);

write('android/app/src/main/res/drawable/ic_launcher_foreground.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/tools/gen-brand.mjs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${A}dp" android:height="${A}dp" android:viewportWidth="${A}" android:viewportHeight="${A}">
    <path android:fillColor="#FFFFFF" android:pathData="${cookieA}" />
${noteGroup(BRAND_DEEP)}
</vector>
`);

// Themed (monochrome) icon: the note is cut out of the cookie with evenOdd.
write('android/app/src/main/res/drawable/ic_launcher_monochrome.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/tools/gen-brand.mjs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${A}dp" android:height="${A}dp" android:viewportWidth="${A}" android:viewportHeight="${A}">
    <path android:fillColor="#FFFFFF" android:fillType="evenOdd" android:pathData="${cookieA} ${transformPath(NOTE, noteScale, 54 - 15, 54 + 15)}" />
</vector>
`);

write('android/app/src/main/res/mipmap-anydpi/ic_launcher.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/tools/gen-brand.mjs -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`);

// Status bar icon: white silhouette only, no cutout detail at 24dp.
write('android/app/src/main/res/drawable/ic_notification.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/tools/gen-brand.mjs -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FFFFFF" android:fillType="evenOdd" android:pathData="${cookie(12, 12, 11)} ${transformPath(NOTE, 14 / 960, 5, 19)}" />
</vector>
`);

// -------------------------------------------------------------------- web
const svgIcon = (size, radius, inset) => {
  const s = (radius * 2 * 0.48) / 960;
  const tx = size / 2 - (960 * s) / 2;
  const ty = size / 2 + (960 * s) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${BRAND}"/><stop offset="1" stop-color="${BRAND_DEEP}"/></linearGradient></defs>
  <rect width="${size}" height="${size}" rx="${inset}" fill="url(#g)"/>
  <path fill="#fff" d="${cookie(size / 2, size / 2, radius)}"/>
  <path fill="${BRAND_DEEP}" transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${s.toFixed(5)})" d="${NOTE}"/>
</svg>
`;
};
write('web/public/icon.svg', svgIcon(64, 25, 14));
// Maskable: full-bleed background, mark inside the 80% safe zone.
write('web/public/icon-maskable.svg', svgIcon(512, 150, 0));
